### ISSUE TITLE
Rethink main menu tiles doodles and prepare descriptions

### ISSUE THREAD

**Issue by bskierys** [bskierys/tabi#44]
- [ ] rethink if every doodle fits as it should for category. Lesser Poland and Subcarpatia should be changed into some other doodles
- [ ] for every category there should be website choosen explaining why it has such doodle. For every website there should be catchy short description (representing first paragraph of it's xontent), and a title
- [ ] preferable english and polish version
- [ ] match the graphical concept

![Voivodeship details.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Voivodeship%20details-282bf7f96551c55c251ba6eb0c734520860c6579ba09d9e7d2d845d42d3b5e58.png)

**Comment by youliab** [comment]
[descriptions_update.txt](https://github.com/bskierys/tabi/files/724839/descriptions_update.txt)
